# Generated by Django 5.1.5 on 2025-03-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('case_title', models.CharField(max_length=100)),
                ('case_description', models.TextField()),
                ('case_location', models.URLField()),
                ('case_image', models.ImageField(upload_to='static/case_images/')),
                ('case_status', models.CharField(max_length=100)),
                ('case_created', models.DateTimeField(auto_now_add=True)),
                ('case_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
