# Generated by Django 5.1.5 on 2025-03-18 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='case_created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='case_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='case_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='case_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='case_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='case_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='case_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='case_updated',
            new_name='updated',
        ),
    ]
