# Generated by Django 5.1.5 on 2025-03-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_case_created_case_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
