# Generated by Django 5.1.5 on 2025-03-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_caseupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='closed_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='caseupdate',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
