# Generated by Django 5.1.5 on 2025-03-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_case_closed_by_case_created_by_caseupdate_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='created_by',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AlterField(
            model_name='caseupdate',
            name='updated_by',
            field=models.CharField(default='fc', max_length=100),
            preserve_default=False,
        ),
    ]
