# Generated by Django 5.1.5 on 2025-03-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_case_created_by_alter_caseupdate_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='created_by',
            field=models.CharField(max_length=100),
        ),
    ]
