# Generated by Django 5.1.5 on 2025-03-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_case_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseupdate',
            name='updated_by',
            field=models.CharField(default='Admin', max_length=100),
        ),
    ]
