# Generated by Django 5.2 on 2025-04-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_caseupdate_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='image',
            field=models.ImageField(upload_to='case_images/'),
        ),
        migrations.AlterField(
            model_name='caseupdate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='case_images/'),
        ),
    ]
